debug: true
log_level: debug
dht_sqlite_path: "./data/dht.db"
grpc_listen: "127.0.0.1:50052"
dht_udp_addr: "0.0.0.0:16881"


pending_table:
  expire_time: 15 # 路由表的超时时间


k_bucket:
  expire_time: 600 # 节点的过期时间
  cron_time: 300 # 5分钟巡检一次, 巡检只对超出5分钟的节点进行 存活检查, 对于超出10分钟的节点, 直接删除
